name: Update CV

on: [push]

jobs:
  make_pdf:
    runs-on: ubuntu-latest
    name: PDF-TEX compiler
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: make pdf in local action
        uses: ./
